
create sequence PROY_PEDIDO_SEQ
/

create sequence PROY_PRODUCTO_SEQ
/

create sequence PROY_PROVEEDOR_SEQ
/


create table PROY_PRODUCTO
(
	IDPRODUCTO NUMBER not null
		constraint PROY_PRODUCTO_PK
			primary key,
	IDPEDIDO NUMBER,
	IDSUCURSAL NUMBER,
	PRECIOPROV NUMBER,
	NOMBRE VARCHAR2(20),
	DESCRIPCION VARCHAR2(20)
)
/

create trigger PROY_PRODUCTO_TRG
	before insert
	on PROY_PRODUCTO
	for each row
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPRODUCTO IS NULL THEN
      SELECT PROY_PRODUCTO_SEQ.NEXTVAL INTO :NEW.IDPRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

create table PROY_PEDIDO
(
	IDPEDIDO NUMBER not null
		constraint PROY_PEDIDO_PK
			primary key,
	IDPROV NUMBER,
	FECHAPEDIDO DATE,
	FECHAENTREGADIST DATE,
	FECHAENTREGASUC DATE,
	PAISORIGEN VARCHAR2(20),
	MODOENVIO VARCHAR2(20)
)
/

create trigger PROY_PEDIDO_TRG
	before insert
	on PROY_PEDIDO
	for each row
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPEDIDO IS NULL THEN
      SELECT PROY_PEDIDO_SEQ.NEXTVAL INTO :NEW.IDPEDIDO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

alter table PROY_PRODUCTO
	add constraint IDPEDIDO_FK
		foreign key (IDPEDIDO) references PROY_PEDIDO
/

create table PROY_PROVEEDOR
(
	IDPROV NUMBER not null
		constraint PROY_PROVEEDOR_PK
			primary key,
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(20),
	CIUDAD VARCHAR2(20),
	ESTADO VARCHAR2(20),
	TELEFONO VARCHAR2(20)
)
/

create trigger PROY_PROVEEDOR_TRG
	before insert
	on PROY_PROVEEDOR
	for each row
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPROV IS NULL THEN
      SELECT PROY_PROVEEDOR_SEQ.NEXTVAL INTO :NEW.IDPROV FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

alter table PROY_PEDIDO
	add constraint IDPROV_FK
		foreign key (IDPROV) references PROY_PROVEEDOR
/



