
  CREATE TABLE "PROY_SUCURSAL" 
   (  "IDSUCURSAL" NUMBER NOT NULL ENABLE, 
  "DIRECCION" VARCHAR2(512 BYTE), 
  "CIUDAD" VARCHAR2(20 BYTE), 
  "ESTADO" VARCHAR2(20 BYTE), 
  "TELEFONO" VARCHAR2(20 BYTE), 
  "NOMBRE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   CONSTRAINT "PROY_SUCURSAL_PK" PRIMARY KEY ("IDSUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_SUCURSAL_TRG" 
BEFORE INSERT ON PROY_SUCURSAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDSUCURSAL IS NULL THEN
      SELECT PROY_SUCURSAL_SEQ.NEXTVAL INTO :NEW.IDSUCURSAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_SUCURSAL_TRG" ENABLE;

  

  CREATE TABLE "PROY_CLIENTE" 
   (	"IDCLIENTE" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(512 BYTE), 
	"APELLIDOS" VARCHAR2(512 BYTE), 
	"DIRECCION" VARCHAR2(512 BYTE), 
	"CIUDAD" VARCHAR2(512 BYTE), 
	"ESTADO" VARCHAR2(512 BYTE), 
	"TELEFONO" VARCHAR2(512 BYTE), 
	"EMAIL" VARCHAR2(512 BYTE), 
	"FECHAREGISTRO" DATE, 
	"SALDO" NUMBER(7,2), 
	 CONSTRAINT "PROY_CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_CLIENTE_TRG" 
BEFORE INSERT ON PROY_CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCLIENTE IS NULL THEN
      SELECT PROY_CLIENTE_SEQ.NEXTVAL INTO :NEW.IDCLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_CLIENTE_TRG" ENABLE;


  CREATE TABLE "PROY_EMPLEADO" 
   (  "IDEMPLEADO" NUMBER NOT NULL ENABLE, 
  "IDSUCURSAL" NUMBER NOT NULL ENABLE, 
  "NOMBRE" VARCHAR2(512 BYTE), 
  "APELLIDOS" VARCHAR2(512 BYTE), 
  "DIRECCION" VARCHAR2(512 BYTE), 
  "TELEFONO" VARCHAR2(512 BYTE), 
  "EMAIL" VARCHAR2(512 BYTE), 
  "FECHAREGISTRO" DATE, 
  "PUESTO" VARCHAR2(512 BYTE), 
  "SALARIO" NUMBER(7,2), 
   CONSTRAINT "PROY_EMPLEADO_PK" PRIMARY KEY ("IDEMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   CONSTRAINT "PROY_EMPLEADO_FK1" FOREIGN KEY ("IDSUCURSAL")
    REFERENCES "PROY_SUCURSAL" ("IDSUCURSAL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_EMPLEADO_TRG" 
BEFORE INSERT ON PROY_EMPLEADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDEMPLEADO IS NULL THEN
      SELECT PROY_EMPLEADO_SEQ.NEXTVAL INTO :NEW.IDEMPLEADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_EMPLEADO_TRG" ENABLE;



  CREATE TABLE "PROY_PRODUCTO" 
   (  "IDPRODUCTO" NUMBER NOT NULL ENABLE, 
  "IDSUCURSAL" NUMBER NOT NULL ENABLE, 
  "NOMBRE" VARCHAR2(512 BYTE) NOT NULL ENABLE, 
  "DESCRIPCION" VARCHAR2(512 BYTE), 
  "FECHALANZAMIENTO" DATE, 
  "ESTADO" VARCHAR2(512 BYTE) DEFAULT 'Nuevo' NOT NULL ENABLE, 
  "DISPONIBLE" NUMBER(2,0), 
  "PRECIOVENTA" NUMBER(6,2), 
  "DESCUENTO" NUMBER(6,2), 
   CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   CONSTRAINT "IDSUCURSAL_SUC_FK" FOREIGN KEY ("IDSUCURSAL")
    REFERENCES "PROY_SUCURSAL" ("IDSUCURSAL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_PRODUCTO_TRG1" 
BEFORE INSERT ON PROY_PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPRODUCTO IS NULL THEN
      SELECT PROY_PRODUCTO_SEQ1.NEXTVAL INTO :NEW.IDPRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_PRODUCTO_TRG1" ENABLE;

  CREATE OR REPLACE TRIGGER "PROY_PRODUCTO_TRG" 
BEFORE INSERT ON PROY_PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_PRODUCTO_TRG" ENABLE;



  CREATE TABLE "PROY_VIDEOJUEGO" 
   (  "IDPRODUCTO" NUMBER NOT NULL ENABLE, 
  "RATING" NUMBER, 
  "CLASIFICACION" VARCHAR2(512 BYTE), 
  "GENERO" VARCHAR2(512 BYTE), 
  "DESARROLLADOR" VARCHAR2(512 BYTE), 
  "JUGADORES" VARCHAR2(512 BYTE), 
   CONSTRAINT "VIDEOJUEGO_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   CONSTRAINT "IDPRODUCTO_SUC_FK" FOREIGN KEY ("IDPRODUCTO")
    REFERENCES "PROY_PRODUCTO" ("IDPRODUCTO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_VIDEOJUEGO_TRG" 
BEFORE INSERT ON PROY_VIDEOJUEGO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_VIDEOJUEGO_TRG" ENABLE;

  CREATE OR REPLACE TRIGGER "PROY_VIDEOJUEGO_TRG1" 
BEFORE INSERT ON PROY_VIDEOJUEGO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.JUGADORES IS NULL THEN
      SELECT PROY_VIDEOJUEGO_SEQ1.NEXTVAL INTO :NEW.JUGADORES FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_VIDEOJUEGO_TRG1" ENABLE;



  CREATE TABLE "PROY_CONSOLA" 
   (  "IDPRODUCTO" NUMBER NOT NULL ENABLE, 
  "EMPRESA" VARCHAR2(512 BYTE), 
  "ALMACENAMIENTO" VARCHAR2(512 BYTE), 
  "ACCESORIOS" VARCHAR2(512 BYTE), 
   CONSTRAINT "PROY_CONSOLA_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   CONSTRAINT "IDPRODUCTO_SUC_CON_FK" FOREIGN KEY ("IDPRODUCTO")
    REFERENCES "PROY_PRODUCTO" ("IDPRODUCTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_CONSOLA_TRG" 
BEFORE INSERT ON PROY_CONSOLA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPRODUCTO IS NULL THEN
      SELECT PROY_CONSOLA_SEQ.NEXTVAL INTO :NEW.IDPRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_CONSOLA_TRG" ENABLE;

  CREATE OR REPLACE TRIGGER "PROY_CONSOLA_TRG1" 
BEFORE INSERT ON PROY_CONSOLA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACCESORIOS IS NULL THEN
      SELECT PROY_CONSOLA_SEQ1.NEXTVAL INTO :NEW.ACCESORIOS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_CONSOLA_TRG1" ENABLE;



  CREATE TABLE "PROY_TRANSACCION" 
   (  "IDTRANSACCION" NUMBER NOT NULL ENABLE, 
  "IDPRODUCTO" NUMBER, 
  "IDCLIENTE" NUMBER, 
  "IDEMPLEADO" NUMBER, 
  "TIPO" VARCHAR2(512 BYTE), 
  "MONTO" NUMBER(6,2), 
  "FECHA" DATE, 
  "METODOPAGO" VARCHAR2(512 BYTE), 
   CONSTRAINT "PROY_TRANSACCION_PK" PRIMARY KEY ("IDTRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   CONSTRAINT "IDPRODUCTO_FK" FOREIGN KEY ("IDPRODUCTO")
    REFERENCES "PROY_PRODUCTO" ("IDPRODUCTO") ON DELETE CASCADE ENABLE, 
   CONSTRAINT "IDCLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
    REFERENCES "PROY_CLIENTE" ("IDCLIENTE") ON DELETE CASCADE ENABLE, 
   CONSTRAINT "IDEMPLEADO_FK" FOREIGN KEY ("IDEMPLEADO")
    REFERENCES "PROY_EMPLEADO" ("IDEMPLEADO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PROY_TRANSACCION_TRG" 
BEFORE INSERT ON PROY_TRANSACCION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDTRANSACCION IS NULL THEN
      SELECT PROY_TRANSACCION_SEQ.NEXTVAL INTO :NEW.IDTRANSACCION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROY_TRANSACCION_TRG" ENABLE;

